### ISSUE TITLE
Documentation for when/how to use "Step"

### ISSUE THREAD

**Issue by moorage** [tensorflow/rust#164]
The C++ and Go SDKs don't have a concept of "Step", to run a graph.  Instead, they specify inputs and outputs , like:

```cpp
  std::vector<Tensor> outputs;
  ClientSession session(root);
  // Run and fetch v
  TF_CHECK_OK(session.Run({v}, &outputs));
  // Expect outputs[0] == [19; -3]
  LOG(INFO) << outputs[0].matrix<float>();
  return 0;
```

It would be great for someone like me who is coming from those SDKs what the concept behind "Step" is in the Rust SDK:

```rust
    // Run the Step
    let mut step = StepWithGraph::new();
    step.add_input(&graph.operation_by_name_required("x")?, 0, &x);
    step.add_input(&graph.operation_by_name_required("y")?, 0, &y);
    let z = step.request_output(&graph.operation_by_name_required("z")?, 0);
    session.run(&mut step)?;
```

Thank you!

**Comment by adamcrume** [comment]
`Step` is just a technicality, not a new concept.  Maybe it would be better named `SessionRunArgs`.

Part of the difficulty is that the Rust tensors are parameterized by element type.  This means that `run` can't return `Vec<Tensor>`, because that's not a type, and it can't return `Vec<Tensor<T>>`, because the result tensors may have different element types.  We could return something like `Vec<Box<AnyTensor>>`, where `AnyTensor` would be a new trait implemented by all tensor types, and which could dynamically be downcast to a specific tensor type.  (Likewise on the input side, we'd have to use something like `&[&AnyTensor]`.)

Is `StepWithGraph` (a.k.a `Step`) difficult or cumbersome to use, or just confusing or surprising based on the other language bindings?  (Not that "just" being different is trivial; we do need to be consistent across languages.)

**Comment by moorage** [comment]
I think my confusion was based on the naming and lack of a similar named construct in the Go & C++ & C SDK.  I think `SessionRunArgs` would clarify it for me.  `Step` makes me wonder if it's a single layer or multiple, but -- I might be alone in that thought :)

**Comment by moorage** [comment]
Oh, and sorry if this is clear to most others, but in the documentation, it would also be nice to understand what `add_input`'s `index` parameter is for.  In my (albeit limited) use of the C++ apis, I haven't had to specify an index when I provide named inputs. 

```rust
pub fn add_input<T: TensorType>(
    &mut self, 
    operation: &Operation, 
    index: c_int, 
    tensor: &'l Tensor<T>
)
```
At: https://tensorflow.github.io/rust/tensorflow/struct.StepWithGraph.html#impl
