### ISSUE TITLE
[Question] Rust -> Wasm

### ISSUE THREAD

**Issue by Krutsch** [tensorflow/rust#207]
I am researching Deep Learning Frameworks in Web for my university paper and just had the crazy Idea of bringing normal TF or TF Rust into the Browser. In the second Case by compiling Rust to WebAssembly and using wasm-bindgen to make WebGL calls.

Could this be faster than TensorFlow.js? It would obviously be a lot heavier to ship but I thought I could be able to have a brider feature set.

Do you have thoughts?

**Comment by adamcrume** [comment]
TensorFlow Rust isn't pure Rust; it uses the TensorFlow C API, which is implemented with C++.  To run that in the browser, you'd have to figure out how to cross-compile the C++ implementation to WASM.  I assume the complications and limitations with that approach are why the TensorFlow team created TensorFlow.js instead.

I'd also recommend asking questions on the [forum](https://groups.google.com/a/tensorflow.org/forum/#!forum/rust) rather than filing issues, since that's a more natural medium for this type of discussion.

**Comment by Krutsch** [comment]
You are right. I will also look for further information on the forum. Thank you 😊
