### ISSUE TITLE
Set data to a Tensor in Row/Column style

### ISSUE THREAD

**Issue by AndreaCatania** [tensorflow/rust#222]
I can create a 2x2 Matrix in this way:
```
let mut matrix = Tensor::new(&[2, 2]);
```
I would like to set its data in row / column style, something like:
```
// Using a macro to generate the Index
matrix[get_index(1, 1)] = 1.0;

// Using a function
matrix.set(1, 1, 1.0);
```

I'm not able to find any function / macro to perform this kind of operation, there is a reason for this?
(In case I'm available to submit a PR to implement it).

**Comment by adamcrume** [comment]
I simply haven't had time to address this, yet, but I know it would make some things a lot more convenient.  Have you considered exactly how it would work?  I don't think a macro is necessary; you could implement `get_index` as a regular function, although it would need to take a slice of integers to support arbitrary tensor ranks.  Since something like `get_index` would need to take the tensor shape as a parameter, it might make more sense to go ahead and create a method on Tensor like `set(&mut self, index: &[u64], value: T)`.

**Comment by AndreaCatania** [comment]
Yep, a function works too. I'll submit a PR
