### ISSUE TITLE
Support Strings as tensor elements

### ISSUE THREAD

**Issue by daschl** [tensorflow/rust#23]
Hi,

here is my simple python-based model:

``` python
import tensorflow as tf

hello = tf.constant('Hello, World!', name = 'hello')

tf.initialize_variables(tf.all_variables(), name = 'init')
definition = tf.Session().graph_def
tf.train.write_graph(definition, 'models', 'hello_world.pb', as_text=False)
```

I've been trying to print `Hello, World` from rust, but I think I saw that the result for String is not yet implemented (https://github.com/google/tensorflow-rust/blob/master/src/lib.rs#L754):

``` rust
extern crate tensorflow;

use tensorflow::{Session, SessionOptions, Step, DataType};
use std::fs::File;
use std::io::Read;


fn main() {
    let filename = "examples/models/hello_world.pb";

    // Initialize Session and load the model.
    let mut session = Session::new(&SessionOptions::new()).unwrap();
    let mut model = Vec::new();
    File::open(filename).unwrap().read_to_end(&mut model);
    session.extend_graph(&model);

    let mut output_step = Step::new();
    let output = output_step.request_output("hello").unwrap();
    session.run(&mut output_step);

    // TODO: String doesn't work yet.
    let result: String = output_step.take_output(output).unwrap().data()[0];
    println!("{:?}", result);
}
```

Is there any way to make it work right now for strings with a workaround? If not, looking forward to when its possible for strings :)

Thanks!

**Comment by adamcrume** [comment]
It's going to be a lot of work to support strings.  Right now, the code has a few assumptions that don't hold for strings:
1. It assumes that the C type and Rust type for tensor elements are bit-for-bit identical.
2. It assumes that the Rust types don't need to be `drop`-ed.  (This is not a huge deal, but it's tricky to get it to drop when necessary and to avoid the overhead when it's not.  It might also not be an issue if we don't actually store `String`s in `Buffer`s.)
3. It assumes that the tensor elements are fixed-sized.

None of these are showstoppers, but it'll take some thought, and I've been treating string support as low-priority, because I assume most real-world uses will be numeric only.

**Comment by daschl** [comment]
I agree, makes sense. I'll come up with numeric hello world cases for now ;)

**Comment by DrRibosome** [comment]
A good example of where strings would be useful in most real world applications is hooking into the save/restore ops provided by the python api under `tf.train.Saver` to specify which file to save/restore variables in/from.

**Comment by DrRibosome** [comment]
As a workaround to getting quick support, we could simply add `String` to the `TensorType` enum and let users encode their strings in binary form via the tensorflow c api `TF_StringEncode`. Then, changing buffer to support accesing raw bytes as `&mut [u8]` users would be able to simply fill the buffer with the encoded string.

The only problem is the deref coercions in buffer, but someone might be able to smooth that out

**Comment by adamcrume** [comment]
I'm working on removing assumptions that don't hold for string tensors.  I should have a pull request (possibly the first in a series, depending on size) ready late next week.

**Comment by daschl** [comment]
👍
