### ISSUE TITLE
Porting Python to Rust question about API

### ISSUE THREAD

**Issue by drbh** [tensorflow/rust#236]
Hey Rust Tensorflow team

I am attempting to port an existing tensorflow powered Python app to Rust. However I am having trouble getting specific Tensors from a model I've loaded in.
```python
    def load_model(self, corrector_model, from_pb=True):
        self.graph = tf.Graph()
        with self.graph.as_default():
            self.sess = tf.Session()
            if from_pb:
                with tf.gfile.GFile(corrector_model, "rb") as f:
                    graph_def = tf.GraphDef()
                    graph_def.ParseFromString(f.read())
                    tf.import_graph_def(graph_def, name="") # If not, name is appended in op name

            else:
                ckpt_path = tf.train.latest_checkpoint(corrector_model)
                saver = tf.train.import_meta_graph('{}.meta'.format(ckpt_path))
                saver.restore(self.sess, ckpt_path)

            self.img = tf.get_default_graph().get_tensor_by_name("img:0")
            self.training = tf.get_default_graph().get_tensor_by_name("training:0")
            self.x = tf.get_default_graph().get_tensor_by_name("X:0")
            self.y = tf.get_default_graph().get_tensor_by_name("Y:0")
            self.w = tf.get_default_graph().get_tensor_by_name("W:0")
            self.h = tf.get_default_graph().get_tensor_by_name("H:0")
```

specifically the 
```python
self.w = tf.get_default_graph().get_tensor_by_name("W:0")
```

I can extract the Operation from the graphs, but cannot seem to get the Tensor from the Operation.... 

My understanding is that a Tensor is a symbolic instance of the output of an Operation? How do I extract that output?

Here is basically what I have in Rust

```rust
    let filename = "./src/models/face_corrector.pb";
    let mut graph = Graph::new();
    let mut proto = Vec::new();
    File::open(filename)
        .unwrap()
        .read_to_end(&mut proto)
        .unwrap();
    graph
        .import_graph_def(&proto, &ImportGraphDefOptions::new())
        .unwrap();
    let session = Session::new(&SessionOptions::new(), &graph).unwrap();

    let img = &graph.operation_by_name("img").unwrap().unwrap();
    let training = &graph.operation_by_name("training").unwrap().unwrap();
    let X = &graph.operation_by_name("X").unwrap().unwrap();
    let Y = &graph.operation_by_name("Y").unwrap().unwrap();
    let W = &graph.operation_by_name("W").unwrap().unwrap();
    let H = &graph.operation_by_name("H").unwrap().unwrap();
```

I'm probably missing a simple command, hope someone can help

Thanks!

**Comment by adamcrume** [comment]
What the Python API calls a Tensor is what the Rust API calls an Output.  (This confusion is unfortunate, but the Rust API simply copied the names used by the C API, which it uses under the hood.)  Rust Tensors basically correspond to NumPy arrays.

The Python
```python
tf.get_default_graph().get_tensor_by_name("H:0")
```

basically converts to
```rust
Output {operation: graph.operation_by_name("H")?, index: 0}
```

To get the actual values, you have to call `Session::run`.  You can see an example of how to do that in the `test_run` test in https://github.com/tensorflow/rust/blob/master/src/session.rs or in https://github.com/tensorflow/rust/blob/master/examples/regression.rs.  The SessionRunArgs methods have separate parameters for Operation and index, rather than taking a single Output; that's a bit of the Rust API that needs to be cleaned up.

By the way, the [mailing list](https://groups.google.com/a/tensorflow.org/forum/#!forum/rust) is a good place to ask for help.
