### ISSUE TITLE
Possible future async interface

### ISSUE THREAD

**Issue by xd009642** [tensorflow/rust#242]
For models like a uni-directional LSTM is there a way you can iteratively feed the model instead of getting the entire input for all timesteps at once? If so adding an interface to drive the model via a `futures::future::Stream` would be really nice from an ergonomics perspective

**Comment by Enet4** [comment]
I'm not entirely sure if I understand this issue, but allow me to expand my thoughts here.

This issue appears to conflate the two distinct aspects of iterative feeding with the async API design in Rust. The graph execution function in the TensorFlow C API is synchronous in nature, as it blocks the caller's thread until an output is obtained. A proper asynchronous abstraction for models would be much more complicated than just wrapping this function into a future type, since that alone would still block the thread.

Ergonomically speaking, it is already possible to prepare an iterator of tensors and feed that to an executor through a `map` adapter, thus obtaining an iterator of outputs, which behaves pretty much like a lazy sequence of items resolved on-demand.

**Comment by xd009642** [comment]
so you don't need to do a fully asynchronous model feeding, just allow a stream of tensors as well as an interator. Things such as the file or process handling parts of tokio can result in blocking calls that stop execution through the nature of the interfaces. 

Alternatively if there was an example for iteratively feeding tensors into a model that could be helpful for myself figuring out how to adapt the streams to map in my own user code. I just had a look in the docs and it doesn't seem to be documented, nor in the examples? And nothing shows up if you search for map or iterator
