### ISSUE TITLE
Release of latest 'master' code in a new Crate v0.15

### ISSUE THREAD

**Issue by deepblue-phoenix** [tensorflow/rust#244]
Thank you for working on this great lib. 
Ive been integrating it recently, and ran into an issue. At the moment Im in need of the tensorflow::io::RecordReader functionality, but Ive noticed that its only present in the master branch after the 0.14 release (which is what the Rust Crate 0.14 is tied to Im assuming). 
I was wondering if there were plans for a Cargo 0.15 release thats based off of the latest version of this repo. I saw that 0.14 version of the crate was released in september last year (Sep 29, 2019).

not sure how much changed, or if there is work-in-progress that prevents that from happening soon. 

thank you very much :) and keep up the great work!

**Comment by deepblue-phoenix** [comment]
Im bypassing this right now by using `git` as the Crate source in my `Cargo.toml`:
`tensorflow = {git = "https://github.com/tensorflow/rust"}`

still it would be nice for that Crate to get updated with new functionality.

**Comment by adamcrume** [comment]
I was planning to release a new version after upgrading to TensorFlow 1.15, but that is turning out to be slightly trickier than past upgrades because they changed the way they're referencing the shared libs.  I may release a new version and then upgrade to TensorFlow 1.15 so we have more time to test the upgrade before releasing it.

**Comment by deepblue-phoenix** [comment]
yeah. I would agree with that. if the transition is trickier then expected I would go ahead and release a new crate version with all the code changes present in master (its been a little while)... and leave the TF 1.15 migration for the next release. 
I dont blame you for preferring to have the version number symmetry (new Crate 0.15 for TF 1.15), but I dont think its too big of a deal if we dont have it :).

if you dont mind me asking, what about dynamic linking of the TF libs has changed with 1.15?
In general I was also hoping that the TF C lib can be statically linked, but it doesnt seem like thats supported at all...

**Comment by adamcrume** [comment]
I'm not actually concerned about the version number symmetry, since we've been out of sync before.  It's just my usual habit to upgrade to the latest TensorFlow version before releasing (excluding the big 2.0 upgrade for the moment).

The difference is that it seems to be trying to link in libtensorflow.so.1 (or libtensorflow.so.1.15.0, I don't remember) instead of libtensorflow.so, which isn't a huge deal, but it means we need to set up symlinks to do it properly, and that has platform-specific behavior, so it's not straightforward.  I also don't have access to a Windows machine with all the tooling installed, so I can't test the Windows build myself.

As far as I'm aware, static linking is still not an option.

**Comment by adamcrume** [comment]
v0.15.0 has been released.

**Comment by deepblue-phoenix** [comment]
awesome! Thank you Adam. :)
