### ISSUE TITLE
Support for TensorFlow 2.4?

### ISSUE THREAD

**Issue by howard-quantrend** [tensorflow/rust#302]
It seems that there are some api changes from TensorFlow 2.3 to 2.4, and this crate doesn't support TensorFlow 2.4 yet. For Apple with M1 chip, the minimum version of TensorFlow that could be installed is 2.4, which means that developers using Apple M1 will encounter some problem use the TensorFlow rust binding, as discussed [here](https://groups.google.com/a/tensorflow.org/g/rust/c/xI3qoezkYtU/m/0wQXhJhQBQAJ). Is there any plan of supporting TensorFlow 2.4? Or any workarounds can be introduced?

**Comment by adamcrume** [comment]
I intend to upgrade the TensorFlow version, but they made a number of breaking changes which is making that difficult.  Upgrading to version 2.4 was blocked by https://github.com/tensorflow/tensorflow/issues/46803, which should be fixed by https://github.com/tensorflow/tensorflow/pull/46804 in version 2.5 (which was released recently), so I'll be trying again.
