### ISSUE TITLE
Cant call concat with vec or slice: trait bound error

### ISSUE THREAD

**Issue by Corallus-Caninus** [tensorflow/rust#325]
when I attempt to call concat I can give neither a vec nor a slice

'let concat = ops::concat(0,vec![input, res_input],  scope)?.into();'
where input and res_input are both tensors of type f32 with same shape.

yields a with trait bound not satisfied error
also the typing in the bindings doesnt make clear how to resolve this.

This project is really exciting thanks.

**Comment by adamcrume** [comment]
Sorry for the delay!  One problem is that 0 can't be passed literally into `ops::concat`, unfortunately.  That has to be wrapped in `ops::constant(0, scope)` to create a `Constant` node.  For the second argument, it looks like we have a bug and are expecting a single tensor rather than a slice of them.

In ops.pbtxt, "Concat" has
```
  input_arg {
    name: "values"
    type_attr: "T"
    number_attr: "N"
  }
```

and it looks like we're ignoring `number_attr`.

**Comment by Corallus-Caninus** [comment]
That makes sense thanks I'm still getting used to working with the functional types and builders. This project is awesome and has taught me a lot about functional programming thanks!
