### ISSUE TITLE
Test that docs build on CI

### ISSUE THREAD

**Issue by martin-t** [tensorflow/rust#335]
Currently the docs are broken https://docs.rs/crate/tensorflow/0.17.0

Idk what the issue is but it should be noted that docs.rs uses nightly. You can look at a hopefully properly implemented GH action for example [here](https://github.com/martin-t/rg3d/blob/ci-fixes/.github/workflows/ci.yml#L101)

**Comment by dskkato** [comment]
The reason [the docs in docs.rs](https://docs.rs/crate/tensorflow/0.17.0) is broken is due to limited network access: see https://github.com/tensorflow/rust/issues/255. Currently, the doc is posted to [github.io](https://tensorflow.github.io/rust/tensorflow/index.html)

Still, I think it is nice to have doc test in GitHub CI. We already have build-check for the doc via `test-all` though.

https://github.com/tensorflow/rust/blob/e4f913433fabb96409bfcd901e9e72282142a6ac/test-all#L55-L56

**Comment by dskkato** [comment]
I am still not sure why issue #255 is not resolved, even though the `private-docs-rs` feature was introduced to avoid downloading large files when building docs.
