### ISSUE TITLE
Release 0.19 w/ TF 2.9.1

### ISSUE THREAD

**Issue by jasonmccampbell** [tensorflow/rust#369]
Hi all, is there a targeted timeframe for a 0.19 release supporting TF 2.9.1 or a set of blocking issues gating it? I am interested in the improved Arm build support. I realize this is a volunteer effort and am happy to help with the release effort where I can.

Regards,
Jason

**Comment by adamcrume** [comment]
I'm working on the release, so that should happen within the next few days unless something comes up.  By the way, the forum (https://discuss.tensorflow.org/c/special-interest-groups/rust/22/none) is a good place to ask general questions.

If you have specific issues that could be improved on ARM, I'd be interested to hear them, or pull requests are always welcome.

**Comment by jasonmccampbell** [comment]
Adam, thanks for the quick response and that's great news about release. I wasn't aware of the discussion forum, but have it bookmarked now. I'll let you know what we find when we start testing on ARM.
