### ISSUE TITLE
Add TF_LoadPluggableDeviceLibrary API

### ISSUE THREAD

**Issue by wangjia184** [tensorflow/rust#381]
Although [`TF_LoadPluggableDeviceLibrary`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api_experimental.cc#L725)  is an experimental API,  it is necessary to use GPU on platform like Mac Arm.

I tried to include this API in code generating but it caused other errors.
Now I always add it manually.

```rust
extern "C" {
    pub fn TF_LoadPluggableDeviceLibrary(
        library_filename: *const ::std::os::raw::c_char,
        status: *mut TF_Status,
    ) -> *mut TF_Library;
}
```

This API had better be included.

**Comment by dskkato** [comment]
Thank you for your inquiry about this issue. As far as I can tell from reading the following forum, I think this is due to the fact that Windows native CUDA support was discontinued in 2.10 and moved to the plugin method in 2.11 and later.

https://discuss.tensorflow.org/t/2-10-last-version-to-support-native-windows-gpu/12404

The corresponding C-API is probably PluggableDevice, and I think we need to resolve the following Issue.

https://github.com/tensorflow/rust/issues/381
