### ISSUE TITLE
TF_AllocateTensor in tensorflow 0.11

### ISSUE THREAD

**Issue by DrRibosome** [tensorflow/rust#42]
It might be possible to let tensorflow manage tensor memory directly with the newly added `TF_AllocateTensor`, instead of handling this with the buffer struct.

**Comment by adamcrume** [comment]
We're using `TF_AllocateTensor` as of e0253112976141f175b8731d63225c7d8054d5f3, although we're still creating a buffer to wrap the data.  It looks like the only places that particular buffer is still used is for the `data()` and `data_mut()` functions (which should be removed, since we've decided to stop exporting the Buffer type) and the `Deref` and `DerefMut` impls, which could be reimplemented.

**Comment by adamcrume** [comment]
We stopped using `Buffer` to store `Tensor` data in f66ed5e38d116c962ed2b2c15db0b81facac61f2.
